In [68]:
import numpy as np
import pandas as pd
from utils import ours_read_csv
from scipy.stats import chi2_contingency
from scipy.stats.contingency import expected_freq


DIR_PATH_TOM = "C:\\Users\\ttomn\\OneDrive\\Desktop\\data-science-transportation-research"
DIR_PATH_MAX = "C:\\Users\\maxba\\Desktop\\Study\\Third Year\\Final Project\\data-science-transportation-research"

In [3]:
df = ours_read_csv(f"{DIR_PATH_TOM}\\timed_with_streets_not_na_Motor_Vehicle_Collisions_-_Crashes.csv")
df

NUMBER OF PERSONS INJURED  NUMBER OF PERSONS KILLED  \
0                              0.0                       0.0   
1                              0.0                       0.0   
2                              0.0                       0.0   
3                              2.0                       0.0   
4                              0.0                       0.0   
...                            ...                       ...   
1750976                        5.0                       0.0   
1750977                        0.0                       0.0   
1750978                        0.0                       0.0   
1750979                        0.0                       0.0   
1750980                        1.0                       0.0   

         NUMBER OF PEDESTRIANS INJURED  NUMBER OF PEDESTRIANS KILLED  \
0                                    0                             0   
1                                    0                             0   
2                                    0                             0   
3                                    0                             0   
4                                    0                             0   
...                                ...                           ...   
1750976                              0                             0   
1750977                              0                             0   
1750978                              0                             0   
1750979                              0                             0   
1750980                              0                             0   

         NUMBER OF CYCLIST INJURED  NUMBER OF CYCLIST KILLED  \
0                                0                         0   
1                                0                         0   
2                                0                         0   
3                                0                         0   
4                                0                         0   
...                            ...                       ...   
1750976                          0                         0   
1750977                          0                         0   
1750978                          0                         0   
1750979                          0                         0   
1750980                          1                         0   

         NUMBER OF MOTORIST INJURED  NUMBER OF MOTORIST KILLED  \
0                                 0                          0   
1                                 0                          0   
2                                 0                          0   
3                                 2                          0   
4                                 0                          0   
...                             ...                        ...   
1750976                           5                          0   
1750977                           0                          0   
1750978                           0                          0   
1750979                           0                          0   
1750980                           0                          0   

          CONTRIBUTING FACTOR VEHICLE 1 CONTRIBUTING FACTOR VEHICLE 2  ...  \
0                           Unspecified                           NaN  ...   
1                                   NaN                           NaN  ...   
2                   Passing Too Closely                   Unspecified  ...   
3                           Unspecified                   Unspecified  ...   
4                   Driver Inexperience                   Unspecified  ...   
...                                 ...                           ...  ...   
1750976  Driver Inattention/Distraction                   Unspecified  ...   
1750977                     Unspecified                           NaN  ...   
1750978           Following Too Closely                   Unspecified  ...   
1750979  Driver Inattention/Distr

In [7]:
df.groupby(['ST_INDEX']).size().sort_values()

ST_INDEX
32885       1
29742       1
91548       1
75445       1
11095       1
         ... 
9821      935
61050     953
65203     959
38565    1003
45576    1101
Length: 75996, dtype: int64

In [16]:
agg_df = ours_read_csv(f"{DIR_PATH_TOM}\\agg_timed_with_streets_not_na_Motor_Vehicle_Collisions_-_Crashes.csv")


In [56]:
one_street = agg_df[agg_df["ST_INDEX"] == 120946]
one_street = one_street[(one_street["YEAR"]<2023)&(one_street["YEAR"]>2012)]
one_street

ST_INDEX  YEAR  MONTH  AMOUNT_ST_INDEX_YEAR_MONTH
1189431    120946  2013      1                           5
1189432    120946  2013      2                           4
1189433    120946  2013      3                           7
1189434    120946  2013      4                           4
1189435    120946  2013      5                           5
...           ...   ...    ...                         ...
1189533    120946  2022      4                           1
1189534    120946  2022      5                           1
1189535    120946  2022      9                           1
1189536    120946  2022     10                           1
1189537    120946  2022     11                           1

[107 rows x 4 columns]

In [57]:
one_street_pivot = one_street.pivot_table(index='YEAR', columns='MONTH', values='AMOUNT_ST_INDEX_YEAR_MONTH',
                                  aggfunc='sum').fillna(0)
one_street_pivot

MONTH   1    2    3    4     5    6    7    8    9    10   11   12
YEAR                                                              
2013   5.0  4.0  7.0  4.0   5.0  6.0  4.0  6.0  5.0  6.0  6.0  2.0
2014   3.0  1.0  2.0  6.0   1.0  7.0  1.0  6.0  3.0  3.0  3.0  5.0
2015   4.0  5.0  6.0  2.0   4.0  4.0  4.0  3.0  7.0  5.0  1.0  2.0
2016   6.0  3.0  3.0  1.0   3.0  5.0  6.0  5.0  3.0  4.0  4.0  3.0
2017   2.0  3.0  5.0  4.0   6.0  6.0  6.0  7.0  6.0  6.0  3.0  6.0
2018   9.0  3.0  5.0  7.0  10.0  7.0  5.0  2.0  1.0  6.0  4.0  6.0
2019   3.0  3.0  3.0  8.0   5.0  4.0  4.0  4.0  5.0  4.0  1.0  5.0
2020   2.0  2.0  1.0  1.0   0.0  0.0  2.0  1.0  0.0  1.0  1.0  1.0
2021   1.0  1.0  0.0  1.0   1.0  0.0  0.0  1.0  1.0  0.0  1.0  2.0
2022   0.0  0.0  1.0  1.0   1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0

In [58]:
result = chi2_contingency(one_street_pivot)
result

(72.56083869685199,
 0.9788121162186892,
 99,
 array([[5.3164557 , 3.79746835, 5.01265823, 5.3164557 , 5.46835443,
         5.92405063, 4.86075949, 5.3164557 , 4.86075949, 5.46835443,
         3.79746835, 4.86075949],
        [3.63291139, 2.59493671, 3.42531646, 3.63291139, 3.73670886,
         4.04810127, 3.32151899, 3.63291139, 3.32151899, 3.73670886,
         2.59493671, 3.32151899],
        [4.16455696, 2.97468354, 3.92658228, 4.16455696, 4.2835443 ,
         4.64050633, 3.80759494, 4.16455696, 3.80759494, 4.2835443 ,
         2.97468354, 3.80759494],
        [4.07594937, 2.91139241, 3.84303797, 4.07594937, 4.19240506,
         4.54177215, 3.72658228, 4.07594937, 3.72658228, 4.19240506,
         2.91139241, 3.72658228],
        [5.3164557 , 3.79746835, 5.01265823, 5.3164557 , 5.46835443,
         5.92405063, 4.86075949, 5.3164557 , 4.86075949, 5.46835443,
         3.79746835, 4.86075949],
        [5.75949367, 4.11392405, 5.43037975, 5.75949367, 5.92405063,
         6.41772152, 5.26

In [60]:
results = [[_ for _ in range(2)] for _ in range(one_street_pivot.shape[0]-1)]
for i in range(one_street_pivot.shape[0]-1):
    print(i)
    results[i][0] = f"{str(2013+i)}-{str(2014+i)}"
    results[i][1] = round(chi2_contingency(one_street_pivot.iloc[i:i+2])[1],4)
results

0
1
2
3
4
5
6
7


ValueError: The internally computed table of expected frequencies has a zero element at (0, 5).

In [65]:
chi2_contingency(one_street_pivot.iloc[6:11])

(20.70747931207115,
 0.9526997879651871,
 33,
 array([[3.86842105, 3.86842105, 3.22368421, 7.09210526, 4.51315789,
         2.57894737, 3.86842105, 3.86842105, 4.51315789, 3.86842105,
         2.57894737, 5.15789474],
        [0.94736842, 0.94736842, 0.78947368, 1.73684211, 1.10526316,
         0.63157895, 0.94736842, 0.94736842, 1.10526316, 0.94736842,
         0.63157895, 1.26315789],
        [0.71052632, 0.71052632, 0.59210526, 1.30263158, 0.82894737,
         0.47368421, 0.71052632, 0.71052632, 0.82894737, 0.71052632,
         0.47368421, 0.94736842],
        [0.47368421, 0.47368421, 0.39473684, 0.86842105, 0.55263158,
         0.31578947, 0.47368421, 0.47368421, 0.55263158, 0.47368421,
         0.31578947, 0.63157895]]))

In [72]:
expected_freq(one_street_pivot.iloc[7:9])

array([[1.71428571, 1.71428571, 0.57142857, 1.14285714, 0.57142857,
        0.        , 1.14285714, 1.14285714, 0.57142857, 0.57142857,
        1.14285714, 1.71428571],
       [1.28571429, 1.28571429, 0.42857143, 0.85714286, 0.42857143,
        0.        , 0.85714286, 0.85714286, 0.42857143, 0.42857143,
        0.85714286, 1.28571429]])